server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import:
      - "loans_application_qa.yml"
      - "loans_application_prod.yml"
    profiles:
      active:
        - "qa"
build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934